matrix:
  include:
    - language: node.js
      node_js: "12.0"
      before_script:
        - cd api
      cache:
        directories:
          - node_modules
      install:
        - yarn global add serverless
        - travis_retry yarn install
        # - cd ${SERVICE_PATH}
        # - travis_retry yarn install
        # - cd -
      script:
        - travis_retry yarn install
        - yarn run jest
        # - ng build --prod
    - language: node.js
      node_js: "12.0"
      before_script:
        - cd webapp
      script:
        - travis_retry yarn install
        - yarn run build
deploy:
  provider: script
  script: bash bin/deploy
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|staging)$