language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
    - ${SERVICE_PATH}/node_modules
install:
    - yarn global add serverless
    - travis_retry yarn install
    - cd ${SERVICE_PATH}
    - travis_retry yarn install
    - cd -
# script:
#     - cd api
#     - yarn run jest
#     - cd -
jobs:
  include:
    # - stage: "Tests"
    #   script:
    #     - cd api
    #     - yarn run jest
    #     - cd -
    # -
      name: "Deploy API"
      env:
        - SERVICE_PATH="api"
    -
      name: "Deploy Webapp"
      env:
        - SERVICE_PATH="webapp"
deploy:
  provider: script
  script: bash bin/deploy
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|staging)$