service: rembourser-api
provider: 
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
functions:
  graphql:
    handler: apollo-server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
plugins: 
  - serverless-webpack
  - serverless-offline
custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    includeModules: true