service: rembourser-api
useDotenv: true
provider: 
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: ${opt:stage}
functions:
  graphql:
    handler: src/apollo-server.graphqlHandler
    environment:
      # TAGGUN_API_KEY: ${env:TAGGUN_API_KEY}
      TAGGUN_API_KEY: ${ssm:/TAGGUN_API_KEY~true}
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
plugins: 
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
custom:
  stage: ${opt:stage, self:provider.stage}
  customDomain:
    domainName: api.rembourser.io
    basePath: ${self:provider.stage}
    stage: ${self:provider.stage}
    # stage: ${opt:stage, self:provider.stage}
    # stage: staging
    certificateName: rembourser.io
    createRoute53Record: true
  webpack:
    includeModules: true